-- MySQL Script generated by MySQL Workbench
-- Sun Apr  1 15:46:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema annotator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema annotator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `annotator` DEFAULT CHARACTER SET latin1 ;
USE `annotator` ;

-- -----------------------------------------------------
-- Table `annotator`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `annotator`.`role` ;

CREATE TABLE IF NOT EXISTS `annotator`.`role` (
  `id` INT NOT NULL,
  `role_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `annotator`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `annotator`.`user` ;

CREATE TABLE IF NOT EXISTS `annotator`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(25) NULL DEFAULT NULL,
  `last_name` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(30) NULL DEFAULT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_user_name_uindex` (`email` ASC),
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role1`
  FOREIGN KEY (`role_id`)
  REFERENCES `annotator`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  AUTO_INCREMENT = 10
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `annotator`.`connections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `annotator`.`connections` ;

CREATE TABLE IF NOT EXISTS `annotator`.`connections` (
  `id` INT NOT NULL,
  `linkedIn_id` VARCHAR(45) NOT NULL,
  `connectionscol` VARCHAR(45) NULL,
  `interests` VARCHAR(5000) NULL,
  `notes` VARCHAR(5000) NULL,
  `user_id1` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_connections_user_idx` (`user_id1` ASC),
  CONSTRAINT `fk_connections_user`
  FOREIGN KEY (`user_id1`)
  REFERENCES `annotator`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;