drop database if exists test_annotator;
create database test_annotator;
use test_annotator;
drop table if exists connections;
create table connections (id int auto_increment primary key, linkedIn_id varchar(45) not null, interests varchar(5000) null, notes varchar(5000) null, user_id int not null, first_name varchar(50) null, last_name varchar(50) null, company varchar(255) null);
create index fk_connections_user_idx on connections (user_id);
drop table if exists role;
create table role(id int auto_increment primary key, role_name varchar(45) null, email varchar(45) null, user_id int null, constraint email_UNIQUE unique (email));
create index role_user_id_fk on role (user_id);
drop table if exists user;
create table user ( id int auto_increment primary key, first_name varchar(25) null, last_name varchar(30) null, email varchar(50) null, password varchar(30) null, constraint users_user_name_uindex unique (email));
alter table connections add constraint fk_connections_user foreign key (user_id) references user (id);
alter table role add constraint role_user_id_fk foreign key (user_id) references user (id);
INSERT INTO user (id, first_name, last_name, email, password) VALUES (1, 'Joe','dCoyne','jcoyne@gmail.com','supersecret1'), (2, 'Fred','Hensen','fhensen@gmail.com','supersecret2'), (3, 'Barney','Curry','bcurry@gmail.com','supersecret3'), (4, 'Karen','Mack','kmack@gmail.com','supersecret4'), (5,'Dianne','Klein','dklein@gmail.com','supersecret5'), (6,'Dawn','Tillman','dtillman@gmail.com','supersecret6');
INSERT INTO ROLE(id, role_name, email, user_id) VALUES (1,'user','fhensen@gmail.com',2);
INSERT INTO connections (id, user_id, linkedin_id, first_name, last_name, notes, interests) VALUES (1, 4, '2354366a', 'Jane', 'Goodall','Sometimes forgets people are not gorillas', 'gorillas, apes'), (2, 3, '543b5st4', 'Joe', 'Schmo', 'Kind of rude', 'cats'), (3, 2, '2345bh2324', 'Ben', 'Rasmus', 'Nerdy', 'Magic the Gathering');