SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE SCHEMA IF NOT EXISTS `test_annotator` DEFAULT CHARACTER SET latin1 ;
USE `test_annotator` ;
DROP TABLE IF EXISTS `test_annotator`.`role` ;
CREATE TABLE IF NOT EXISTS `test_annotator`.`role` (`id` INT NOT NULL,`role_name` VARCHAR(45) NULL,`email` VARCHAR(45) NULL,PRIMARY KEY (`id`),UNIQUE INDEX `email_UNIQUE` (`email` ASC)) ENGINE = InnoDB;
DROP TABLE IF EXISTS `test_annotator`.`user` ;
CREATE TABLE IF NOT EXISTS `test_annotator`.`user` (`id` INT(11) NOT NULL AUTO_INCREMENT, `first_name` VARCHAR(25) NULL DEFAULT NULL,`last_name` VARCHAR(30) NULL DEFAULT NULL,`email` VARCHAR(50) NULL DEFAULT NULL,`password` VARCHAR(30) NULL DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `users_user_name_uindex` (`email` ASC)) ENGINE = InnoDB AUTO_INCREMENT = 10 DEFAULT CHARACTER SET = latin1;
DROP TABLE IF EXISTS `test_annotator`.`connections` ;
CREATE TABLE IF NOT EXISTS `test_annotator`.`connections` (`id` INT NOT NULL, `linkedIn_id` VARCHAR(45) NOT NULL, `interests` VARCHAR(5000) NULL, `notes` VARCHAR(5000) NULL, `user_id` INT(11) NOT NULL, PRIMARY KEY (`id`), INDEX `fk_connections_user_idx` (`user_id` ASC), CONSTRAINT `fk_connections_user` FOREIGN KEY (`user_id`) REFERENCES `test_annotator`.`user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION) ENGINE = InnoDB;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
insert into user(id,first_name,last_name,email,password) values (1, "joan","smith","jsmith@gmail.com","password");
insert into user(id,first_name,last_name,email,password) values (2, "jane","doe","jsmitafasfh@gmail.com","password");
insert into user(id,first_name,last_name,email,password) values (3, "joasdfasdfan","smiasdfasdfth","jsmith@gmaiasdfl.com","password");
insert into connections (id,linkedin_id, interests, notes, user_id) values (1, "1stewtaw1", "cats and dogs", "likes animals", 1);
insert into connections (id,linkedin_id, interests, notes, user_id) values (2, "1sefgtl22", "cats and giraffes and dogs", "likes animals", 2);
insert into connections (id,linkedin_id, interests, notes, user_id) values (3, "125524ll1", "cats faces' but not dogs", "likes animals and stuff", 3);
insert into connections (id,linkedin_id, interests, notes, user_id) values (4, "1352dfaw1", "cats", "likes few animals", 2);